print_info() {
    prin "${blue}プレゼント・デイ、プレゼント・タイム"
    info "${green}OS" distro
    info "${green}Uptime" uptime
    info "${green}Shell" shell
    info "${green}WM" wm
    info "${green}Theme" theme
    info "${green}Icons" icons
    info "${green}Terminal" term
#    info "${green}Terminal Font" term_font
    info "${green}CPU" cpu
    info "${green}Memory" memory
    prin "${red}⬤ \n \n ${green}⬤  \n \n ${yellow}⬤  \n \n ${blue}⬤  \n \n ${magenta}⬤  \n \n ${cyan}⬤  \n \n ${reset}⬤  \n \n "
}

distro_shorthand="on"
os_arch="off"
uptime_shorthand="tiny"
memory_percent="off"
memory_unit="gib"
shell_path="on"
shell_version="off"
cpu_brand="on"
cpu_temp="off"
underline_enabled="off"
separator=":"
image_backend="chafa"
image_source="$HOME/.config/neofetch/lain.jpg"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="40%"
gap=6
stdout="off"

red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
magenta="\033[1;35m"
cyan="\033[1;36m"
reset="\033[0m"

# Show Desktop Environment version
#
# Default: 'on'
# Values:  'on', 'off'
# Flag:    --de_version
de_version="on"
